apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mw-lang-detector
  namespace: mw-agent-ns
spec:
  selector:
    matchLabels:
      app: mw-lang-detector  
  template:
    metadata:
      labels:
        app: mw-lang-detector
    spec:
      containers:
      - image: ghcr.io/middleware-labs/mw-lang-detector:0.1.2
        imagePullPolicy: IfNotPresent
        name: mw-lang-detector
        command: ["/app/mw-lang-detector"]
        args: ["start"]
        env:
          - name: MW_TARGET
            value: "MW_TARGET_VALUE"
          - name: MW_API_KEY
            value: "MW_API_KEY_VALUE"
          - name: MW_KUBE_CLUSTER_NAME
            value: "MW_KUBE_CLUSTER_NAME_VALUE"
          - name: MW_RELEASE_NAMESPACE
            value: mw-agent-ns
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MW_API_URL_FOR_LANG_AGGREGATOR
            value: "http://mw-lang-aggregator.mw-agent-ns.svc.cluster.local:8080"
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi        
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /proc
          mountPropagation: None
          name: proc
          readOnly: true
      hostPID: true
      securityContext:
        runAsUser: 0
      serviceAccountName: mw-lang-detector
      volumes:
      - hostPath:
          path: /proc
        name: proc