kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    k8s-app: mw-app
  name: mw-role-update
  namespace: "NAMESPACE_VALUE"
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "update", "create"]
- apiGroups: ["apps"]
  resources: ["daemonsets", "deployments"]
  verbs: ["get", "update"]
