kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: mw-kube-agent
  namespace: "NAMESPACE_VALUE"
spec:
  selector:
    matchLabels:
      app: mw-app
  template:
    metadata:
      labels:
        app: mw-app
        k8s-app: mw-app
    spec:
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - operator: "Exists"
        effect: "NoSchedule"
      - operator: "Exists"
        effect: "NoExecute"
      hostNetwork: true
      volumes:
        - name: mw-daemonset-otel-config-volume
          configMap:
            name: mw-daemonset-otel-config
            items:
              - key: otel-config
                path: otel-config-daemonset.yaml
        # volume binding for log collection 
        - name: varlog
          hostPath:
            path: /var/log
        - name: varrun
          hostPath:
            path: /var/run/docker.sock
        - name: runcontainerd
          hostPath:
            path: /run/containerd/containerd.sock
        # volume binding for log collection
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
      containers:
        - args:
            - mw-agent
            - start
            - --otel-config-file
            - /app/otel-config-daemonset.yaml            
          env:
            - name: MW_TARGET
              value: "TARGET_VALUE"
            - name: MW_API_KEY
              value: "MW_API_KEY_VALUE"
            - name: MW_DOCKER_ENDPOINT
              value: "MW_DOCKER_ENDPOINT_VALUE"
            - name: MW_KUBE_CLUSTER_NAME
              value: "MW_KUBE_CLUSTER_NAME_VALUE"
            - name: MW_NAMESPACE
              value: "NAMESPACE_VALUE"
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          image: ghcr.io/middleware-labs/mw-kube-agent:MW_VERSION_VALUE
          imagePullPolicy: IfNotPresent
          name: mw-kube-agent
          securityContext:
            allowPrivilegeEscalation: true
          volumeMounts:
          - name: mw-daemonset-otel-config-volume
            mountPath: /app
          - mountPath: /var/log
            name: varlog
            readOnly: true
          - mountPath: /var/run/docker.sock
            name: varrun
            readOnly: true
          - mountPath: /run/containerd/containerd.sock
            name: runcontainerd
            readOnly: true
          - mountPath: /var/lib/docker/containers
            name: varlibdockercontainers
            readOnly: true
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      restartPolicy: Always
      serviceAccountName: mw-service-account